# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: napari
author: The napari team
logo: assets/logo.ico
# only_build_toc_files: true

# Cache notebook execution for each build. This is useful for speeding up
# subsequent builds during deveopment.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Information about where the book exists on the web
repository:
  url: https://github.com/napari-staging-site/napari-staging-site.github.io # Online location of your book
  branch: master # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinx.ext.viewcode
    - sphinx.ext.napoleon
    - sphinx.ext.autodoc
    - sphinx_autodoc_typehints
    - sphinx.ext.autosummary
    - sphinx.ext.intersphinx

  config:
    autosummary_generate: True
    autosummary_imported_members: True
    # Skip checking these files because they slow down the overall build time
    exclude_patterns:
      - _build
      - node_modules
      - theme/js
      - theme/scss
    html_theme: furo
    # (WIP) napari theme
    # html_theme: napari
    # html_theme_path:
    #   - theme
    pygments_style: solarized-dark
    templates_path:
      - '_templates'
    intersphinx_mapping:
      python:
        - "https://docs.python.org/3"
        - null
      numpy:
        - "https://docs.scipy.org/doc/numpy/"
        - null
      napari_plugin_engine:
        - "https://napari-plugin-engine.readthedocs.io/en/latest/"
        - "https://napari-plugin-engine.readthedocs.io/en/latest/objects.inv"
